name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

permissions:
  contents: write  # 👈 This allows the bot to push to the repo

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://medium.com/feed/@vimal.surani"
          commit_message: "Updated with the latest blog posts"
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
